# Generated by Django 5.1.5 on 2025-01-30 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job_seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_listings",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.joblisting",
            ),
        ),
    ]
